//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XViewCodeSamples.Views.SystemViews {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemLayout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemLayout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XViewCodeSamples.Views.SystemViews.SystemLayout", typeof(SystemLayout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Tridion.ContentManager.CommunicationManagement;
        ///
        ///using XView;
        ///
        ///using XViewCodeSamples.Common;
        ///using XViewCodeSamples.Resources;
        ///
        ///namespace XViewCodeSamples.Views.SystemViews
        ///{
        ///    public class CustomControllerView : ControllerView&lt;SampleContext&gt;
        ///    {
        ///        public CustomControllerView(SampleContext context) : base(context)
        ///        {
        ///        }
        ///
        ///        protected override void InitializeRender()
        ///        {
        ///            base.InitializeRender();
        ///            this.EnableOutputDecoration =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomControllerView {
            get {
                return ResourceManager.GetString("CustomControllerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using XView;
        ///
        ///using XViewCodeSamples.Resources;
        ///
        ///namespace XViewCodeSamples.Views.SystemViews
        ///{
        ///    public class PreviewErrorView : View&lt;InvalidOutputContext&gt;
        ///    {
        ///        protected override void InitializeRender()
        ///        {
        ///            base.InitializeRender();
        ///            this.EnableOutputDecoration = false;
        ///            this.EnableOutputValidation = false;
        ///        }
        ///
        ///        protected override string Render()
        ///        {
        ///            switch (this.Model.OutputType)
        ///            {
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PreviewErrorView {
            get {
                return ResourceManager.GetString("PreviewErrorView", resourceCulture);
            }
        }
    }
}
