//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chimote.Tridion.Templating.Intranet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chimote.Tridion.Templating.Intranet.Resources.ResourceFiles", typeof(ResourceFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;config&gt;
        ///  &lt;development&gt;
        ///    &lt;entry key=&quot;ContentManagerUrl&quot;&gt;http://tridiondev.mycompany.com&lt;/entry&gt;
        ///    &lt;entry key=&quot;LiveHostname&quot;&gt;live.dev.mycompany.com&lt;/entry&gt;
        ///    &lt;entry key=&quot;StagingHostname&quot;&gt;staging.dev.mycompany.com&lt;/entry&gt;
        ///    &lt;entry key=&quot;StagingTargetUri&quot;&gt;tcm:0-18-65537&lt;/entry&gt;
        ///    &lt;entry key=&quot;MediaManagerHostname&quot;&gt;mycompany-accept.sdlmedia.com&lt;/entry&gt;
        ///    &lt;entry key=&quot;TempFolderPath&quot;&gt;C:\Temp&lt;/entry&gt;
        ///  &lt;/development&gt;
        ///  &lt;test&gt;
        ///    &lt;entry key=&quot;ContentMana [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnvironmentConfiguration {
            get {
                return ResourceManager.GetString("EnvironmentConfiguration", resourceCulture);
            }
        }
    }
}
