//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chimote.Tridion.Templating.Intranet.Views.SystemViews {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chimote.Tridion.Templating.Intranet.Views.SystemViews.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///    .typeName { color: #00a1de; }
        ///
        ///    .code { color: maroon; }
        ///
        ///    .error {
        ///        color: red;
        ///        font-size: 1.1em;
        ///    }
        ///
        ///    a {
        ///        text-decoration: none;
        ///        color: #00a1de;
        ///    }
        ///
        ///    a:hover { text-decoration: underline; }
        ///&lt;/style&gt;
        ///&lt;pre&gt;
        ///__  ___   ___               ___         _           _ _         
        ///\ \/ \ \ / (_)_____ __ __  / __|___ _ _| |_ _ _ ___| | |___ _ _ 
        /// &gt;  &lt; \ V /| / -_\ V  V / | (__/ _ | &apos; |  _| &apos;_/ _ | | / -_| &apos;_|
        ////_/\_\ \_/ | [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntranetControllerView {
            get {
                return ResourceManager.GetString("IntranetControllerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using XView;
        ///
        ///namespace Chimote.Tridion.Templating.Intranet.Views.SystemViews
        ///{
        ///    public class PreviewErrorView : View&lt;InvalidOutputContext&gt;
        ///    {
        ///        protected override void InitializeRender()
        ///        {
        ///            base.InitializeRender();
        ///            this.EnableOutputDecoration = false;
        ///            this.EnableOutputValidation = false;
        ///        }
        ///
        ///        protected override string Render()
        ///        {
        ///            switch (this.Model.OutputType)
        ///            {
        ///                case ViewOutp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PreviewErrorView {
            get {
                return ResourceManager.GetString("PreviewErrorView", resourceCulture);
            }
        }
    }
}
